sudo: required

services:
  - docker

before_install: 
  - docker build -t kerestes/docker-react -f Dockerfile.dev .

script: 
  - docker run kerestes/docker-react npm run test -- --coverage --watchAll=false

deploy: 
  provider: elasticbeanstalk
  region: "eu-north-1a"
  app: "docker-react"
  env: "Docker-react-env-1"
  bucket_name: "elasticbeanstalk-eu-north-1-572701481508"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"