sudo: required
services:
  - docker

before_install: 
  - docker build -t kerestes/docker-react -f Dockerfile.dev .

script: 
  - docker run kerestes/docker-react npm run test -- --coverage --watchAll=false